package com.beyondthelimits.block;

import com.beyondthelimits.block.entity.SignalMachineBlockEntity;
import net.minecraft.block.Block;
import net.minecraft.block.BlockEntityProvider;
import net.minecraft.block.BlockState;
import net.minecraft.block.entity.BlockEntity;
import net.minecraft.block.entity.BlockEntityTicker;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.util.ActionResult;
import net.minecraft.util.hit.BlockHitResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import org.jetbrains.annotations.Nullable;

/**
 * The source of the Signal.
 *
 * <p>Buried thousands of blocks underground inside a bunker that was never generated by Minecraft.
 * It transmits a radio-like loop with no explanation and no quest marker. When a player finally
 * finds it, the machine displays coordinates — and the coordinates are the player's own current
 * position, because the machine has been transmitting *about the player* the entire time.</p>
 */
public class SignalMachineBlock extends Block implements BlockEntityProvider {
	public SignalMachineBlock(Settings settings) {
		super(settings);
	}

	@Nullable
	@Override
	public BlockEntity createBlockEntity(BlockPos pos, BlockState state) {
		return new SignalMachineBlockEntity(pos, state);
	}

	@Nullable
	@Override
	public <T extends BlockEntity> BlockEntityTicker<T> getTicker(World world, BlockState state, BlockEntityType<T> type) {
		if (world.isClient()) {
			return null;
		}

		return (tickWorld, pos, tickState, blockEntity) -> {
			if (blockEntity instanceof SignalMachineBlockEntity machine) {
				machine.serverTick();
			}
		};
	}

	@Override
	public ActionResult onUse(BlockState state, World world, BlockPos pos, PlayerEntity player, BlockHitResult hit) {
		if (world.isClient()) {
			return ActionResult.SUCCESS;
		}

		if (world.getBlockEntity(pos) instanceof SignalMachineBlockEntity machine) {
			return machine.onUse(player);
		}

		return ActionResult.PASS;
	}
}
