#!/usr/bin/env python3
"""Beyond Minecraft's deterministic authoring compiler. Python 3.11+, standard library only.

Possible seeds are effectively unbounded; a built mod deliberately registers 1..32 realms.
It does NOT run in Minecraft, mutate live registries, copy copyrighted textures, or execute
untrusted scripts. Its manifest allows --check to detect stale/missing/extra generated files.

Every realm now declares five materials (stratum / surface / crystal / flora / core), its own
terrain recipe, its own decoration set, its own atmosphere and its own creature roster. Four of
the twelve default realms are generated by custom Java chunk generators (bubble hub, white
labyrinth, Menger fractal, temporal reach) rather than by vanilla noise settings; the compiler
only writes their biome + dimension documents and lets the audited generator classes place blocks.
"""
from __future__ import annotations
import argparse
import copy
import hashlib
import json
import math
from pathlib import Path
import random
import struct
import sys
import zlib

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SEED = 84921603
DEFAULT_REALMS = 12

# id, name, base, glow, sky, fog, terrain recipe, pattern, decoration, ambient
# The first eight are the original catalog's worlds, rebuilt with their own materials, flora,
# cores, decoration sets and creature rosters. The last four are the generated spaces the
# Tear opens onto: a bubble hub, an endless white labyrinth, a fractal sponge and a temporal
# reach reached through a wormhole.
REALMS = [
    dict(name="Lucent Canopy", base=(38, 117, 86), glow=(116, 240, 192), sky=0x122238, fog=0x78CCA1,
         terrain="canopy", pattern="grain", decor=["trees", "pillars", "geode", "waterfall"],
         ambient=.24, time=6000, spawns=[("beyond:realm_critter", 12), ("minecraft:bat", 6)]),
    dict(name="The Violet Fold", base=(68, 43, 111), glow=(200, 125, 255), sky=0x1C123D, fog=0xAF83FF,
         terrain="spire", pattern="crack", decor=["pillars", "crystal_cluster", "geode", "blob"],
         ambient=.22, time=15000, spawns=[("beyond:realm_critter", 12), ("minecraft:enderman", 2)]),
    dict(name="Cinder Cathedral", base=(92, 37, 31), glow=(255, 136, 52), sky=0x2A111C, fog=0xDB7752,
         terrain="canyon", pattern="strata", decor=["pillars", "blob", "lava_lake"],
         ambient=.28, time=18000, spawns=[("beyond:realm_critter", 10), ("minecraft:magma_cube", 4)]),
    dict(name="Boreal Memory", base=(80, 112, 143), glow=(142, 227, 255), sky=0x172C49, fog=0x99D8ED,
         terrain="plateau", pattern="scale", decor=["pillars", "crystal_cluster", "ice_spikes"],
         ambient=.30, time=6000, spawns=[("beyond:realm_critter", 10), ("minecraft:polar_bear", 2)]),
    dict(name="Rose Continuum", base=(123, 65, 117), glow=(255, 171, 221), sky=0x30243D, fog=0xF29BDA,
         terrain="bloom", pattern="fibre", decor=["trees", "blob", "geode"],
         ambient=.26, time=12000, spawns=[("beyond:realm_critter", 14), ("minecraft:bee", 6)]),
    dict(name="Pelagic Dream", base=(25, 75, 108), glow=(60, 214, 237), sky=0x081C30, fog=0x4DB5D7,
         terrain="ocean", pattern="wave", decor=["coral", "waterfall", "blob"],
         ambient=.20, time=6000, spawns=[("beyond:realm_critter", 8), ("minecraft:glow_squid", 6)]),
    dict(name="Obsidian Hymn", base=(44, 43, 64), glow=(144, 253, 230), sky=0x101020, fog=0xB0DFD3,
         terrain="cavern", pattern="facet", decor=["crystal_cluster", "pillars", "geode"],
         ambient=.14, time=18000, spawns=[("beyond:realm_critter", 12), ("minecraft:silverfish", 4)]),
    dict(name="The Ochre Archive", base=(123, 106, 58), glow=(255, 231, 155), sky=0x312B28, fog=0xD4C097,
         terrain="dune", pattern="grid", decor=["pillars", "ruin", "blob"],
         ambient=.30, time=9000, spawns=[("beyond:realm_critter", 10), ("minecraft:husk", 3)]),
    dict(name="The Vesper Between", base=(222, 228, 235), glow=(150, 210, 255), sky=0x05070E, fog=0xC8D6E4,
         terrain="between", pattern="bubble", decor=["bubbles", "puzzle", "abyss"],
         ambient=.42, time=6000, spawns=[("beyond:realm_critter", 6)]),
    dict(name="The Endless Labyrinth", base=(236, 238, 240), glow=(120, 126, 138), sky=0x0B0D12, fog=0xF2F4F7,
         terrain="labyrinth", pattern="grid", decor=["maze", "stairs", "particles"],
         ambient=.52, time=6000, spawns=[("beyond:realm_critter", 8), ("minecraft:endermite", 2)]),
    dict(name="The Fractal Hollow", base=(212, 216, 224), glow=(96, 168, 255), sky=0x04060C, fog=0xE8EDF5,
         terrain="fractal", pattern="sponge", decor=["sponge", "stairs", "void_drops"],
         ambient=.40, time=6000, spawns=[("beyond:realm_critter", 8)]),
    dict(name="The Temporal Reach", base=(86, 78, 132), glow=(255, 214, 122), sky=0x1A1330, fog=0xE0C89A,
         terrain="temporal", pattern="strata", decor=["pillars", "ruin", "blob", "geode"],
         ambient=.26, time=23000, spawns=[("beyond:realm_critter", 12), ("minecraft:witch", 2)]),
]

KINDS = ("stratum", "surface", "crystal", "flora", "core")
# Which block of a realm is "soil" (tagged dirt), and which materials are luminous.
GLOW_KINDS = {"crystal": 12, "flora": 4}
SOFT_KINDS = {"flora"}          # decorative blocks that behave like leaves/moss
CORE_KINDS = {"core"}           # deep stone-like blocks


def png(width, height, rgba):
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
    rows = b"".join(b"\0" + bytes(rgba[y * width * 4:(y + 1) * width * 4]) for y in range(height))
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(rows, 9)) + chunk(b"IEND", b""))


def _mix(a, b, t):
    return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))


def _shift(color, turn):
    """Deterministic palette rotation for echo realms beyond the twelve named worlds."""
    if turn <= 0:
        return color
    rotate = turn % 3
    shifted = tuple(color[(i + rotate) % 3] for i in range(3))
    factor = 1.0 - .10 * ((turn % 4) + 1)
    return tuple(max(6, min(250, int(v * factor))) for v in shifted)


def block_texture(seed, base, glow, kind, pattern):
    """16x16 material. Every realm gets its own pattern family, not just a recolour."""
    rng = random.Random(seed ^ (zlib.crc32(kind.encode()) & 0xFFFF))
    frames = 4 if kind == "crystal" else 1
    noise = [rng.uniform(-1, 1) for _ in range(256)]
    pixels = []
    for frame in range(frames):
        for y in range(16):
            for x in range(16):
                g = noise[(y * 16 + x + frame * 7) & 255]
                vein = abs(math.sin(x * .42 + math.sin(y * .68) * 1.6)) < .20
                bevel = .80 if x in (0, 15) or y in (0, 15) else 1.0
                if kind == "crystal":
                    pulse = .62 + .20 * math.sin(frame * math.pi / 2 + (x + y) * .28)
                    color = [c * (pulse if vein else .25 + g * .06) * bevel for c in glow]
                elif kind == "flora":
                    dense = 1.0 if rng.random() < .18 else 0.0
                    color = [(base[i] * .55 + glow[i] * .45) * (.72 + g * .20 + dense * .20) for i in range(3)]
                elif kind == "core":
                    color = [base[i] * .38 * (1 + g * .30) + (glow[i] * .07 if pattern == "facet" else 0) for i in range(3)]
                elif kind == "surface":
                    color = [c * (.72 + g * .22) for c in _mix(base, glow, .30)]
                else:  # stratum, and any realm-specific substitute
                    color = [base[i] * (1 + g * .25) + (glow[i] * .20 if vein else 0) for i in range(3)]

                # Pattern overlays. These are the realm's "material identity".
                t = (x + y) / 30.0
                if pattern == "strata":
                    shade = .78 + .22 * math.sin(y * 1.15 + g * .4)
                    color = [c * shade for c in color]
                elif pattern == "crack":
                    crack = min(abs(math.sin(x * .8 + g * 2.0)), abs(math.cos(y * .7 - g * 1.4)))
                    if crack < .10:
                        color = [c * .35 for c in color]
                elif pattern == "scale":
                    cell = ((x // 4) + (y // 4)) % 2
                    color = [c * (.86 + .14 * cell) for c in color]
                elif pattern == "grid":
                    if x % 8 == 0 or y % 8 == 0:
                        color = [c * .28 for c in color]
                    elif x % 8 in (1, 7) or y % 8 in (1, 7):
                        color = [c * 1.22 for c in color]
                elif pattern == "facet":
                    color = [c * (.70 + .30 * abs(math.sin(x * .9) * math.cos(y * .9))) for c in color]
                elif pattern == "wave":
                    color = [c * (.80 + .24 * math.sin((x * .6 + y * .25))) for c in color]
                elif pattern == "fibre":
                    color = [c * (.86 + .18 * math.sin(y * 2.1 + x * .3)) for c in color]
                elif pattern == "sponge":
                    if (x % 8 in (2, 5)) and (y % 8 in (2, 5)):
                        color = [c * .30 for c in color]
                elif pattern == "bubble":
                    r = math.hypot(x - 7.5, y - 7.5)
                    color = [c * (.65 + .75 * math.exp(-((r - 5.0) ** 2) * 1.4)) for c in color]
                elif pattern == "grain":
                    color = [c * (1.0 + .06 * math.sin(t * 12.0)) for c in color]
                pixels.extend([min(255, max(0, round(c))) for c in color] + [255])
    return png(16, 16 * frames, pixels)


def icon(kind, size=32):
    pixels = []
    for y in range(size):
        for x in range(size):
            u, v = (x + .5) / size * 2 - 1, (y + .5) / size * 2 - 1
            r = math.hypot(u, v)
            color = (0, 0, 0, 0)
            if kind == "reality_knife":
                blade = abs(u + v + .22) < .19 and -.77 < v < .19
                handle = abs(u + v + .2) < .23 and .15 < v < .73
                if blade: color = (166, 247, 248, 255) if u + v < -.22 else (111, 63, 204, 255)
                if handle: color = (52, 37, 77, 255)
                if abs(v - .19) < .08 and abs(u) < .4: color = (226, 181, 101, 255)
            elif kind == "radiate_reality_glasses":
                lens = abs(abs(u) - .37) < .28 and abs(v) < .28
                frame = abs(abs(u) - .37) < .34 and abs(v) < .36
                bridge = abs(u) < .15 and abs(v) < .08
                if frame or bridge: color = (213, 179, 104, 255)
                if lens: color = (69 + int(70 * (1 - abs(v))), 177, 205, 230)
            elif kind == "field_guide":
                if abs(u) < .61 and abs(v) < .79: color = (22, 42, 51, 255)
                if -.59 < u < -.46 and abs(v) < .79: color = (181, 142, 78, 255)
                if .15 < abs(v) < .20 and abs(u) < .30: color = (113, 219, 217, 255)
                if abs(math.hypot(u - .07, v) - .30) < .055: color = (228, 193, 126, 255)
                if math.hypot(u - .07, v) < .09: color = (211, 251, 238, 255)
            elif kind == "reality_tear":
                # A ragged vertical cut with a bright edge: the tool that rips the membrane open.
                cut = abs(u + .18 * math.sin(v * 7.0)) < .16
                if cut and abs(v) < .88: color = (18, 16, 30, 255)
                edge = abs(abs(u + .18 * math.sin(v * 7.0)) - .16) < .05 and abs(v) < .88
                if edge: color = (196, 140, 255, 255)
                if cut and r < .55: color = (86, 232, 226, 255)
                if abs(u) < .05 and abs(v) > .80: color = (226, 181, 101, 255)
            else:
                shape = abs(u) * .8 + abs(v) < .77
                cut = abs(u + .15 * math.sin(v * 8)) < .085
                if shape:
                    color = (180, 138, 245, 255) if u < 0 else (73, 222, 225, 255)
                    if kind == "shattered_relic" and cut: color = (19, 17, 33, 255)
                    if abs(v) < .05 or abs(u) < .05: color = (235, 234, 255, 255)
            pixels.extend(color)
    return png(size, size, pixels)


def critter_texture(seed, base, glow):
    """Deliberately mottled so any face mapping reads as hide: safe for the code-built quadruped.

    The model's eye cubes sample the painted glow patch at (56,56); the spine strip at x=62 gives
    the back a readable ridge. Everything else is noise, which is what makes blind UV mapping safe.
    """
    rng = random.Random(seed ^ 0x5EED)
    size = 64
    pixels = []
    for y in range(size):
        for x in range(size):
            g = rng.uniform(-1, 1) * .5 + rng.uniform(-1, 1) * .3
            belly = max(0.0, 1.0 - abs(y - 46) / 12.0) * .5
            spot = 1.0 if rng.random() < .04 else 0.0
            c = _mix(base, glow, .18 + belly * .55 + spot * .5)
            c = [v * (1 + g * .28) for v in c]
            pixels.extend([min(255, max(0, round(v))) for v in c] + [255])
    def put(x, y, color):
        pixels[(y * size + x) * 4:(y * size + x + 1) * 4] = list(min(255, max(0, c)) for c in color) + [255]
    for x in range(56, 64):
        for y in range(56, 64):
            put(x, y, (min(255, glow[0] + 70), min(255, glow[1] + 70), min(255, glow[2] + 70)))
    for y in range(2, 50):
        put(62, y, tuple(int(v * 1.25) for v in glow))
    return png(size, size, pixels)


def density(kind, **args):
    return {"type": "minecraft:" + kind, **args}


def terrain_router(recipe, key, theme, rng):
    """One genuinely different terrain equation per realm family."""
    surface = density("y_clamped_gradient", from_y=-40 + theme * 3, to_y=216 - theme * 2, from_value=-1.5, to_value=1.5)
    primary = density("noise", noise=f"beyond:{key}_terrain", xz_scale=.65 + theme * .065, y_scale=1.15 + theme * .06)
    secondary = density("noise", noise=f"beyond:{key}_detail", xz_scale=1.7 + theme * .11, y_scale=.55)
    if recipe == "canopy":
        shelves = density("mul", argument1=secondary, argument2=density("abs", argument=density("add",
            argument1=-16.0, argument2=density("mul", argument1=8.0, argument2=secondary))))
        body = density("add", argument1=density("mul", argument1=1.4, argument2=primary), argument2=shelves)
        final = density("add", argument1=body, argument2=density("mul", argument1=-1.0, argument2=density("abs", argument=surface)))
    elif recipe == "spire":
        ridges = density("mul", argument1=secondary, argument2=density("abs", argument=secondary))
        final = density("add", argument1=density("mul", argument1=2.2, argument2=density("add",
            argument1=density("mul", argument1=.9, argument2=primary), argument2=ridges)),
            argument2=density("mul", argument1=-1.15, argument2=density("abs", argument=surface)))
    elif recipe == "canyon":
        plateaus = density("clamp", input=density("mul", argument1=3.0, argument2=surface), min=-1.0, max=1.0)
        final = density("add", argument1=density("mul", argument1=.55, argument2=primary),
            argument2=density("mul", argument1=-1.0, argument2=density("abs", argument=plateaus)))
    elif recipe == "plateau":
        stepped = density("clamp", input=density("mul", argument1=2.0, argument2=surface), min=-1.0, max=1.0)
        # The gradient increases with Y: invert it so this plateau solidifies below its crown
        # and reliably leaves open sky above, rather than filling the realm to the build limit.
        quantized = density("mul", argument1=-.5, argument2=density("add", argument1=stepped, argument2=density("squeeze", argument=stepped)))
        final = density("add", argument1=density("mul", argument1=.9, argument2=primary), argument2=quantized)
    elif recipe == "bloom":
        bulbs = density("mul", argument1=primary, argument2=density("mul", argument1=secondary, argument2=2.2))
        final = density("add", argument1=density("mul", argument1=1.8, argument2=bulbs),
            argument2=density("mul", argument1=-1.0, argument2=density("abs", argument=surface)))
    elif recipe == "ocean":
        seabed = density("add", argument1=.25, argument2=density("mul", argument1=.45, argument2=primary))
        islands = density("mul", argument1=secondary, argument2=density("abs", argument=density("add",
            argument1=-30.0, argument2=density("mul", argument1=12.0, argument2=primary))))
        final = density("add", argument1=seabed, argument2=islands)
    elif recipe == "cavern":
        solid = density("add", argument1=-.35, argument2=density("mul", argument1=1.1, argument2=primary))
        hollow = density("mul", argument1=-2.2, argument2=density("abs", argument=density("add",
            argument1=-6.0, argument2=density("mul", argument1=10.0, argument2=secondary))))
        final = density("add", argument1=solid, argument2=hollow)
    elif recipe == "dune":
        ripples = density("mul", argument1=.6, argument2=density("squeeze", argument=secondary))
        final = density("add", argument1=density("add", argument1=.15, argument2=density("mul", argument1=.5, argument2=primary)),
            argument2=density("mul", argument1=-1.0, argument2=density("abs", argument=density("add",
                argument1=ripples, argument2=density("mul", argument1=.6, argument2=surface)))))
    else:  # temporal and any fallback share the original gentle recipe
        final = density("add", argument1=density("mul", argument1=1.4, argument2=primary),
            argument2=density("add", argument1=-.06, argument2=density("mul", argument1=-1.0, argument2=density("abs", argument=surface))))
    amplitude = [1.0, round(rng.uniform(.6, 1.2), 4), .45, .18]
    detail_amplitude = [1.0, round(rng.uniform(.4, .9), 4), .3]
    return final, amplitude, detail_amplitude


def decoration(feature_lists, realm, key, blocks, theme):
    """Realm-specific flora, structures and set dressing. Returns placed-feature links."""
    flora, crystal, core, surface = blocks[3], blocks[2], blocks[4], blocks[1]
    placed = {}
    # crystal towers exist everywhere, with per-realm heights
    placed[f"{key}_pillars"] = dict(configured=("minecraft:block_column", {
        "layers": [{"height": {"type": "minecraft:uniform", "min_inclusive": 3, "max_inclusive": 18 + theme},
                    "provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{crystal}"}}}],
        "direction": "up", "allowed_placement": {"type": "minecraft:matching_blocks", "blocks": ["minecraft:air"]},
        "prioritize_tip": False}),
        placement=[{"type": "minecraft:count", "count": 7}, {"type": "minecraft:in_square"},
                   {"type": "minecraft:heightmap", "heightmap": "WORLD_SURFACE_WG"}, {"type": "minecraft:biome"}])
    if "trees" in realm["decor"]:
        placed[f"{key}_trees"] = dict(configured=("minecraft:tree", {
            "dirt_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{surface}"}},
            "trunk_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{core}"}},
            "foliage_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{flora}"}},
            "trunk_placer": {"type": "minecraft:straight_trunk_placer", "base_height": 5, "height_rand_a": 3, "height_rand_b": 2},
            "foliage_placer": {"type": "minecraft:blob_foliage_placer", "radius": 2, "offset": 0, "height": 3},
            "minimum_size": {"type": "minecraft:two_layers_feature_size", "limit": 1, "lower_size": 0, "upper_size": 1},
            "decorators": [], "ignore_vines": True, "force_dirt": True}),
            placement=[{"type": "minecraft:count", "count": 6}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:heightmap", "heightmap": "WORLD_SURFACE_WG"}, {"type": "minecraft:biome"}])
    if "crystal_cluster" in realm["decor"]:
        placed[f"{key}_cluster"] = dict(configured=("minecraft:ore", {
            "size": 6, "discard_chance_on_air_exposure": 0.0,
            "targets": [{"target": {"predicate_type": "minecraft:always_true"},
                         "state": {"Name": f"beyond:{crystal}"}}]}),
            placement=[{"type": "minecraft:count", "count": 9}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:heightmap", "heightmap": "WORLD_SURFACE_WG"}, {"type": "minecraft:biome"}])
    if "blob" in realm["decor"]:
        placed[f"{key}_blob"] = dict(configured=("minecraft:ore", {
            "size": 11, "discard_chance_on_air_exposure": 0.05,
            "targets": [{"target": {"predicate_type": "minecraft:always_true"},
                         "state": {"Name": f"beyond:{flora}"}}]}),
            placement=[{"type": "minecraft:count", "count": 5}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:heightmap", "heightmap": "MOTION_BLOCKING"}, {"type": "minecraft:biome"}])
    if "geode" in realm["decor"]:
        placed[f"{key}_geode"] = dict(configured=("minecraft:geode", {
            "blocks": {"filling_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{crystal}"}},
                       "inner_layer_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{flora}"}},
                       "alternate_inner_layer_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{crystal}"}},
                       "middle_layer_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{core}"}},
                       "outer_layer_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{blocks[0]}"}},
                       "inner_placements": [{"Name": f"beyond:{crystal}"}],
                       "cannot_replace": "#minecraft:features_cannot_replace",
                       "invalid_blocks": "#minecraft:geode_invalid_blocks"},
            "layers": {"filling": 1.7, "inner_layer": 2.2, "middle_layer": 3.2, "outer_layer": 4.2},
            "crack": {"generate_crack_chance": 0.95, "base_crack_size": 2.0, "crack_point_offset": 2},
            "use_potential_placements_chance": 0.35, "use_alternate_layer0_chance": 0.15,
            "placements_require_layer0_alternate": True, "invalid_blocks_threshold": 1}),
            placement=[{"type": "minecraft:count", "count": 2}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:height_range", "height": {"type": "minecraft:trapezoid",
                        "min_inclusive": {"absolute": -48}, "max_inclusive": {"absolute": 40}}},
                       {"type": "minecraft:biome"}])
    if "waterfall" in realm["decor"] or "coral" in realm["decor"] or "lava_lake" in realm["decor"]:
        fluid = "minecraft:lava" if "lava_lake" in realm["decor"] else "minecraft:water"
        placed[f"{key}_fluid"] = dict(configured=("minecraft:lake", {
            "fluid": {"type": "minecraft:simple_state_provider", "state": {"Name": fluid}},
            "barrier": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{core}"}}}),
            placement=[{"type": "minecraft:count", "count": 3}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:height_range", "height": {"type": "minecraft:uniform",
                        "min_inclusive": {"absolute": 0}, "max_inclusive": {"absolute": 90}}},
                       {"type": "minecraft:biome"}])
    if "ice_spikes" in realm["decor"]:
        placed[f"{key}_spikes"] = dict(configured=("minecraft:block_column", {
            "layers": [{"height": {"type": "minecraft:uniform", "min_inclusive": 3, "max_inclusive": 11},
                        "provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{crystal}"}}}],
            "direction": "up", "allowed_placement": {"type": "minecraft:matching_blocks",
                                                     "blocks": [f"beyond:{surface}", f"beyond:{blocks[0]}"]},
            "prioritize_tip": False}),
            placement=[{"type": "minecraft:count", "count": 12}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:heightmap", "heightmap": "WORLD_SURFACE_WG"}, {"type": "minecraft:biome"}])
    if "ruin" in realm["decor"]:
        placed[f"{key}_ruins"] = dict(configured=("minecraft:block_pile", {
            "state_provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{blocks[0]}"}}}),
            placement=[{"type": "minecraft:count", "count": 6}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:heightmap", "heightmap": "WORLD_SURFACE_WG"}, {"type": "minecraft:biome"}])
    if "bubbles" in realm["decor"]:
        placed[f"{key}_bubble_growth"] = dict(configured=("minecraft:ore", {
            "size": 14, "discard_chance_on_air_exposure": 0.0,
            "targets": [{"target": {"predicate_type": "minecraft:always_true"},
                         "state": {"Name": f"beyond:{crystal}"}}]}),
            placement=[{"type": "minecraft:count", "count": 24}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:height_range", "height": {"type": "minecraft:uniform",
                        "min_inclusive": {"absolute": -20}, "max_inclusive": {"absolute": 120}}},
                       {"type": "minecraft:biome"}])
    # Generated spaces (bubble hub, labyrinth, fractal) dress themselves in Java, but every realm
    # still ships at least one flora scatter and one crystal vein so the biome is never bare.
    if len(placed) < 2 or realm["terrain"] in ("between", "labyrinth", "fractal", "temporal"):
        placed[f"{key}_scatter"] = dict(configured=("minecraft:block_column", {
            "layers": [{"height": {"type": "minecraft:uniform", "min_inclusive": 1, "max_inclusive": 3},
                        "provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{flora}"}}}],
            "direction": "up", "allowed_placement": {"type": "minecraft:matching_blocks", "blocks": ["minecraft:air"]},
            "prioritize_tip": False}),
            placement=[{"type": "minecraft:count", "count": 8}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:heightmap", "heightmap": "WORLD_SURFACE_WG"}, {"type": "minecraft:biome"}])
    if realm["terrain"] in ("between", "labyrinth", "fractal"):
        placed[f"{key}_veins"] = dict(configured=("minecraft:block_column", {
            "layers": [{"height": {"type": "minecraft:uniform", "min_inclusive": 2, "max_inclusive": 9},
                        "provider": {"type": "minecraft:simple_state_provider", "state": {"Name": f"beyond:{crystal}"}}}],
            "direction": "down", "allowed_placement": {"type": "minecraft:matching_blocks", "blocks": ["minecraft:air"]},
            "prioritize_tip": False}),
            placement=[{"type": "minecraft:count", "count": 5}, {"type": "minecraft:in_square"},
                       {"type": "minecraft:height_range", "height": {"type": "minecraft:uniform",
                        "min_inclusive": {"absolute": -40}, "max_inclusive": {"absolute": 80}}},
                       {"type": "minecraft:biome"}])
    return placed


def generate(seed=DEFAULT_SEED, count=DEFAULT_REALMS):
    if not 1 <= count <= 32:
        raise ValueError("Realm count must be 1..32; live registry growth is deliberately forbidden")
    rng = random.Random(seed)
    files = {}
    def put(path, value):
        files[path] = value if isinstance(value, bytes) else (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode()
    lang = {
        "itemGroup.beyond": "Beyond Minecraft",
        "tag.item.beyond.realm_crystals": "Realm Crystals",
        "key.category.beyond": "Beyond Minecraft",
        "key.beyond.guide": "Open the Field Guide",
        "key.beyond.mandela": "Cycle reality (glasses)",
        "key.beyond.panic": "Toggle all Beyond visual effects",
        "key.beyond.scale": "Grow / shrink",
        "key.beyond.tear": "Tear the fabric",
        "item.beyond.reality_knife": "Reality Knife",
        "item.beyond.shattered_relic": "Shattered Relic",
        "item.beyond.reality_tear": "Reality Tear",
        "item.beyond.radiate_reality_glasses": "Radiate Reality Glasses",
        "item.beyond.field_guide": "The Beyond Field Guide",
        "item.beyond.scale_prism": "Scale Prism",
        "entity.beyond.realm_critter": "Realm Critter",
        "key.beyond.hud": "Toggle Beyond diagnostics",
    }
    catalog = {"schema": 2, "seed": seed, "realms": []}
    dirt, pickaxe, crystals, soft = [], [], [], []
    template = json.loads((ROOT / "tools/templates/end-1.21.1.json").read_text())
    for i in range(count):
        source = REALMS[i % len(REALMS)]
        realm = source if i < len(REALMS) else dict(source, name=source["name"] + f" / Echo {i // len(REALMS) + 1}",
            base=_shift(source["base"], i // len(REALMS)), glow=_shift(source["glow"], (i // len(REALMS)) * 2))
        key = f"realm_{i:02}"
        theme = i % len(REALMS)
        name, base, glow = realm["name"], realm["base"], realm["glow"]
        realm_seed = rng.randrange(1, 1 << 23)  # exactly representable in a float shader uniform
        blocks = [f"{key}_{kind}" for kind in KINDS]
        custom = realm["terrain"] in ("between", "labyrinth", "fractal")
        catalog["realms"].append({"id": key, "name": name, "theme": theme, "color": realm["fog"],
                                  "seed": realm_seed, "blocks": blocks, "terrain": realm["terrain"],
                                  "ambient": realm["ambient"], "time": realm["time"],
                                  "materials": len(KINDS), "generator": "beyond:" + realm["terrain"] if custom else "minecraft:noise"})
        for kind, block in zip(KINDS, blocks):
            put(f"assets/beyond/textures/block/{block}.png", block_texture(realm_seed, base, glow, kind, realm["pattern"]))
            if kind == "crystal":
                put(f"assets/beyond/textures/block/{block}.png.mcmeta", {"animation": {"frametime": 8, "interpolate": True}})
            put(f"assets/beyond/blockstates/{block}.json", {"variants": {"": {"model": f"beyond:block/{block}"}}})
            put(f"assets/beyond/models/block/{block}.json", {"parent": "minecraft:block/cube_all", "textures": {"all": f"beyond:block/{block}"}})
            put(f"assets/beyond/models/item/{block}.json", {"parent": f"beyond:block/{block}"})
            put(f"data/beyond/loot_table/blocks/{block}.json", {
                "type": "minecraft:block", "pools": [{"rolls": 1, "entries": [{"type": "minecraft:item", "name": f"beyond:{block}"}],
                "conditions": [{"condition": "minecraft:survives_explosion"}]}]})
            lang[f"block.beyond.{block}"] = f"{name} {kind.title()}"
            pickaxe.append(f"beyond:{block}")
            if kind == "flora":
                soft.append(f"beyond:{block}")
        dirt.append(f"beyond:{blocks[1]}")
        crystals.append(f"beyond:{blocks[2]}")
        echo = f"{key}_echo"
        lang[f"item.beyond.{echo}"] = name + " Echo"
        put(f"assets/beyond/textures/item/{echo}.png", block_texture(realm_seed ^ 9741, base, glow, "surface", realm["pattern"]))
        put(f"assets/beyond/models/item/{echo}.json", {"parent": "minecraft:item/generated", "textures": {"layer0": f"beyond:item/{echo}"}})
        put(f"data/beyond/recipe/{echo}.json", {"type": "minecraft:crafting_shapeless", "ingredients": [{"item": f"beyond:{blocks[2]}"}],
            "result": {"id": f"beyond:{echo}", "count": 4}})
        put(f"data/beyond/recipe/{key}_crystal.json", {"type": "minecraft:crafting_shaped", "pattern": ["EE", "EE"],
            "key": {"E": {"item": f"beyond:{echo}"}}, "result": {"id": f"beyond:{blocks[2]}"}})
        placed = decoration({}, realm, key, blocks, theme)
        features = [[] for _ in range(11)]
        placed_links = []
        slot = 4
        for feature_key, definition in placed.items():
            configured, placement = definition["configured"], definition["placement"]
            put(f"data/beyond/worldgen/configured_feature/{feature_key}.json", {"type": configured[0], "config": configured[1]})
            put(f"data/beyond/worldgen/placed_feature/{feature_key}.json", {"feature": f"beyond:{feature_key}", "placement": placement})
            features[min(slot, 10)].append(f"beyond:{feature_key}")
            placed_links.append(feature_key)
            slot = min(slot + 1, 10)
        spawners = {}
        for entity, weight in realm["spawns"]:
            # 1.21.1's biome SpawnGroup codec uses the lower-case registry ids.
            group = "water_creature" if entity.endswith("squid") else ("ambient" if entity.endswith("bat") else "creature")
            spawners.setdefault(group, []).append({"type": entity, "weight": weight, "minCount": 1, "maxCount": 3})
        put(f"data/beyond/worldgen/biome/{key}.json", {
            "has_precipitation": False, "temperature": .6, "downfall": 0.0,
            "effects": {"sky_color": realm["sky"], "fog_color": realm["fog"], "water_color": 0x2A899C,
                        "water_fog_color": 0x133745, "grass_color": realm["fog"], "foliage_color": realm["fog"],
                        "mood_sound": {"sound": "minecraft:ambient.cave", "tick_delay": 6000, "offset": 2.0, "block_search_extent": 8}},
            "spawners": spawners, "spawn_costs": {}, "carvers": {}, "features": features})
        dimension_type = "beyond:void" if realm["terrain"] in ("between", "labyrinth", "fractal") else "beyond:membrane"
        if custom:
            # Custom Java generators receive the realm's own materials, so a sponge, a maze and a
            # bubble hub are built from that realm's palette rather than a hardcoded look.
            generator = {"type": f"beyond:{realm['terrain']}_generator",
                         "biome_source": {"type": "minecraft:fixed", "biome": f"beyond:{key}"},
                         "material": f"beyond:{blocks[0]}", "accent": f"beyond:{blocks[1]}"}
            if realm["terrain"] == "between":
                generator["shell"] = f"beyond:{blocks[2]}"
            put(f"data/beyond/dimension/{key}.json", {"type": dimension_type, "generator": generator})
        else:
            final, amplitude, detail_amplitude = terrain_router(realm["terrain"], key, theme, rng)
            settings = copy.deepcopy(template)
            settings.update(default_block={"Name": f"beyond:{blocks[0]}"}, legacy_random_source=False)
            settings["noise"] = {"min_y": -64, "height": 384, "size_horizontal": 1, "size_vertical": 2}
            settings["noise_router"] = {k: 0.0 for k in settings["noise_router"]}
            settings["noise_router"].update(
                final_density=density("squeeze", argument=density("interpolated", argument=final)),
                initial_density_without_jaggedness=final,
                barrier=density("noise", noise="minecraft:aquifer_barrier", xz_scale=1.0, y_scale=0.5))
            settings["surface_rule"] = {"type": "minecraft:sequence", "sequence": [
                {"type": "minecraft:condition", "if_true": {"type": "minecraft:stone_depth", "offset": 0,
                    "add_surface_depth": False, "secondary_depth_range": 0, "surface_type": "floor"},
                 "then_run": {"type": "minecraft:block", "result_state": {"Name": f"beyond:{blocks[1]}"}}},
                {"type": "minecraft:condition", "if_true": {"type": "minecraft:stone_depth", "offset": 3,
                    "add_surface_depth": True, "secondary_depth_range": 0, "surface_type": "floor"},
                 "then_run": {"type": "minecraft:block", "result_state": {"Name": f"beyond:{blocks[4]}"}}},
                {"type": "minecraft:block", "result_state": {"Name": f"beyond:{blocks[0]}"}}]}
            put(f"data/beyond/worldgen/noise_settings/{key}.json", settings)
            put(f"data/beyond/worldgen/noise/{key}_terrain.json", {"firstOctave": -6 - i % 2, "amplitudes": amplitude})
            put(f"data/beyond/worldgen/noise/{key}_detail.json", {"firstOctave": -2 + i % 3, "amplitudes": detail_amplitude})
            put(f"data/beyond/dimension/{key}.json", {"type": dimension_type, "generator": {"type": "minecraft:noise",
                "biome_source": {"type": "minecraft:fixed", "biome": f"beyond:{key}"}, "settings": f"beyond:{key}"}})
    put("data/beyond/dimension_type/membrane.json", {
        "ultrawarm": False, "natural": False, "piglin_safe": False, "respawn_anchor_works": False,
        "bed_works": False, "has_raids": False, "has_skylight": True, "has_ceiling": False,
        "coordinate_scale": 1.0, "ambient_light": .22, "logical_height": 384, "min_y": -64, "height": 384,
        "infiniburn": "#minecraft:infiniburn_overworld", "effects": "minecraft:overworld", "fixed_time": 6000,
        "monster_spawn_block_light_limit": 0, "monster_spawn_light_level": 0})
    # The generated spaces are unlit or softly lit; their ambience comes from the renderer and soundscape.
    put("data/beyond/dimension_type/void.json", {
        "ultrawarm": False, "natural": False, "piglin_safe": False, "respawn_anchor_works": False,
        "bed_works": False, "has_raids": False, "has_skylight": False, "has_ceiling": False,
        "coordinate_scale": 1.0, "ambient_light": .62, "logical_height": 384, "min_y": -64, "height": 384,
        "infiniburn": "#minecraft:infiniburn_overworld", "effects": "minecraft:the_end", "fixed_time": 6000,
        "monster_spawn_block_light_limit": 0, "monster_spawn_light_level": 0})
    for tag, values in (("dirt", dirt), ("mineable/pickaxe", pickaxe), ("leaves", soft)):
        put(f"data/minecraft/tags/block/{tag}.json", {"replace": False, "values": values})
    put("data/beyond/tags/item/realm_crystals.json", {"replace": False, "values": crystals})
    ingredients = {
        "reality_knife": ["minecraft:iron_sword", "minecraft:echo_shard", "minecraft:ender_pearl"],
        "shattered_relic": ["minecraft:echo_shard", "minecraft:ender_eye", "minecraft:amethyst_shard"],
        "reality_tear": ["minecraft:iron_sword", "minecraft:amethyst_shard", "minecraft:phantom_membrane"],
        "radiate_reality_glasses": ["minecraft:spyglass", "minecraft:ender_eye", "minecraft:gold_ingot"],
        "field_guide": ["minecraft:book", "minecraft:amethyst_shard"],
        "scale_prism": ["minecraft:amethyst_shard", "minecraft:clock", "minecraft:ender_pearl"],
    }
    for item, recipe in ingredients.items():
        put(f"assets/beyond/textures/item/{item}.png", icon(item))
        put(f"assets/beyond/models/item/{item}.json", {"parent": "minecraft:item/handheld" if item in ("reality_knife", "reality_tear") else "minecraft:item/generated",
            "textures": {"layer0": f"beyond:item/{item}"}})
        put(f"data/beyond/recipe/{item}.json", {"type": "minecraft:crafting_shapeless", "ingredients": [{"item": r} for r in recipe], "result": {"id": f"beyond:{item}"}})
        lang[f"item.beyond.{item}"] = item.replace("_", " ").title()
    # Four critter skins, one per four-realm family, drawn from that family's first palette.
    for variant in range(4):
        source = REALMS[variant % len(REALMS)]
        put(f"assets/beyond/textures/entity/realm_critter_{variant}.png", critter_texture(seed + variant * 7717, source["base"], source["glow"]))
    put("data/beyond/loot_table/entities/realm_critter.json", {"type": "minecraft:entity", "pools": []})
    armor = [0] * (64 * 32 * 4)
    for y in range(11, 14):
        for x in range(0, 32):
            lens = 8 <= x < 11 or 13 <= x < 16
            color = (105, 213, 233, 190) if lens and y == 12 else (203, 172, 103, 255)
            armor[(y * 64 + x) * 4:(y * 64 + x + 1) * 4] = color
    put("assets/beyond/textures/models/armor/radiate_layer_1.png", png(64, 32, armor))
    put("assets/beyond/textures/models/armor/radiate_layer_2.png", png(64, 32, [0] * (64 * 32 * 4)))
    put("assets/beyond/icon.png", icon("shattered_relic", 128))
    put("assets/beyond/catalog.json", catalog)
    put("assets/beyond/lang/en_us.json", json.loads(json.dumps(lang)))
    manifest = {"schema": 2, "seed": seed, "realms": count, "files": {k: hashlib.sha256(v).hexdigest() for k, v in sorted(files.items())}}
    put("beyond-generated.json", manifest)
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--realms", type=int, default=DEFAULT_REALMS)
    parser.add_argument("--output", type=Path, default=ROOT / "src/main/generated")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = generate(args.seed, args.realms)
    output = args.output.resolve()
    actual = {p.relative_to(output).as_posix() for p in output.rglob("*") if p.is_file()} if output.exists() else set()
    if args.check:
        errors = [key for key, data in files.items() if not (output / key).is_file() or (output / key).read_bytes() != data]
        extra = sorted(actual - files.keys())
        if errors or extra:
            print("Generated resources differ:", *errors, *extra, sep="\n  ", file=sys.stderr)
            return 1
        print(f"PASS: {len(files)} generated resources are byte-for-byte reproducible ({args.realms} realms, seed {args.seed}).")
        return 0
    # Do not silently remove unrelated files or follow symlinks in a user-supplied output directory.
    old_manifest = output / "beyond-generated.json"
    old_keys = set(json.loads(old_manifest.read_text())["files"]) | {"beyond-generated.json"} if old_manifest.is_file() else set()
    if actual - old_keys - files.keys():
        raise ValueError("Output directory contains unowned files; choose an empty directory")
    for key in files.keys() | old_keys:
        target = output / key
        if not target.resolve().is_relative_to(output):
            raise ValueError("Output path escapes generated directory")
    for key in sorted(old_keys - files.keys()):
        (output / key).unlink(missing_ok=True)
    for key, data in sorted(files.items()):
        target = output / key
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    print(f"Generated {len(files)} resources; {args.realms} realms, {args.realms * len(KINDS)} blocks, {args.realms} echo items. Seed {args.seed}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
