package dev.logan.beyond.client.entity;

import dev.logan.beyond.BeyondMinecraft;
import dev.logan.beyond.entity.RealmCritter;
import net.minecraft.client.render.entity.EntityRendererFactory;
import net.minecraft.client.render.entity.MobEntityRenderer;
import net.minecraft.client.render.entity.model.EntityModelLayer;
import net.minecraft.util.Identifier;

/** Four realm-family skins, all generated by the mod's authoring script. */
public class RealmCritterRenderer extends MobEntityRenderer<RealmCritter, RealmCritterModel> {
    public static final EntityModelLayer LAYER = new EntityModelLayer(BeyondMinecraft.id("realm_critter"), "main");
    private static final Identifier[] TEXTURES = {
        BeyondMinecraft.id("textures/entity/realm_critter_0.png"),
        BeyondMinecraft.id("textures/entity/realm_critter_1.png"),
        BeyondMinecraft.id("textures/entity/realm_critter_2.png"),
        BeyondMinecraft.id("textures/entity/realm_critter_3.png"),
    };
    public RealmCritterRenderer(EntityRendererFactory.Context context) {
        super(context, new RealmCritterModel(context.getPart(LAYER)), 0.5f);
    }
    @Override public Identifier getTexture(RealmCritter entity) { return TEXTURES[Math.floorMod(entity.getVariant(), TEXTURES.length)]; }
}
