package dev.logan.beyondthreshold;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

import java.util.ArrayList;
import java.util.List;

/**
 * GENERATED by onepac.py — seed 1337, 16 variants, 5 dimensions.
 * Do not edit by hand: rerun onepac.py for a new multiverse.
 */
@SuppressWarnings("unused")
public final class BTTGeneratedContent {
	public record GenDim(String id, String biome) { }

	public static final List<GenDim> DIMENSIONS = new ArrayList<>();
	static {
		DIMENSIONS.add(new GenDim("membrane", "plains"));
		DIMENSIONS.add(new GenDim("aurora", "snowy_plains"));
		DIMENSIONS.add(new GenDim("backrooms", "desert"));
		DIMENSIONS.add(new GenDim("ember", "badlands"));
		DIMENSIONS.add(new GenDim("mycelia", "mushroom_fields"));
	}

	private static final Block[][] BLOCKS = new Block[4][]; // grass stone log leaves
	private static final BlockItem[][] ITEMS = new BlockItem[4][];

	public static void register() {
		BLOCKS[0] = new Block[16];
		ITEMS[0] = new BlockItem[16];
		for (int i = 0; i < 16; i++) {
			Block b = new Block(AbstractBlockSettingsCopy(Blocks.GRASS_BLOCK));
			BLOCKS[0][i] = b;
			Registry.register(Registries.BLOCK, new Identifier(BeyondTheThreshold.MOD_ID, "vb_grass" + i), b);
			BlockItem bi = new BlockItem(b, new Item.Settings());
			ITEMS[0][i] = bi;
			Registry.register(Registries.ITEM, new Identifier(BeyondTheThreshold.MOD_ID, "vb_grass" + i), bi);
		}
		BLOCKS[1] = new Block[16];
		ITEMS[1] = new BlockItem[16];
		for (int i = 0; i < 16; i++) {
			Block b = new Block(AbstractBlockSettingsCopy(Blocks.STONE));
			BLOCKS[1][i] = b;
			Registry.register(Registries.BLOCK, new Identifier(BeyondTheThreshold.MOD_ID, "vb_stone" + i), b);
			BlockItem bi = new BlockItem(b, new Item.Settings());
			ITEMS[1][i] = bi;
			Registry.register(Registries.ITEM, new Identifier(BeyondTheThreshold.MOD_ID, "vb_stone" + i), bi);
		}
		BLOCKS[2] = new Block[16];
		ITEMS[2] = new BlockItem[16];
		for (int i = 0; i < 16; i++) {
			Block b = new Block(AbstractBlockSettingsCopy(Blocks.OAK_LOG));
			BLOCKS[2][i] = b;
			Registry.register(Registries.BLOCK, new Identifier(BeyondTheThreshold.MOD_ID, "vb_log" + i), b);
			BlockItem bi = new BlockItem(b, new Item.Settings());
			ITEMS[2][i] = bi;
			Registry.register(Registries.ITEM, new Identifier(BeyondTheThreshold.MOD_ID, "vb_log" + i), bi);
		}
		BLOCKS[3] = new Block[16];
		ITEMS[3] = new BlockItem[16];
		for (int i = 0; i < 16; i++) {
			Block b = new Block(AbstractBlockSettingsCopy(Blocks.OAK_LEAVES));
			BLOCKS[3][i] = b;
			Registry.register(Registries.BLOCK, new Identifier(BeyondTheThreshold.MOD_ID, "vb_leaves" + i), b);
			BlockItem bi = new BlockItem(b, new Item.Settings());
			ITEMS[3][i] = bi;
			Registry.register(Registries.ITEM, new Identifier(BeyondTheThreshold.MOD_ID, "vb_leaves" + i), bi);
		}
	}

	private static net.minecraft.block.AbstractBlock.Settings AbstractBlockSettingsCopy(Block from) {
		return net.minecraft.block.AbstractBlock.Settings.copyOf(from);
	}

	public static int variantCount() {
		return 16;
	}

	public static net.minecraft.block.BlockState blockState(int kind, int variant) {
		return BLOCKS[kind & 3][Math.floorMod(variant, variantCount())].getDefaultState();
	}

	public static BlockItem pickBlock(int kind, int variant) {
		return ITEMS[kind & 3][Math.floorMod(variant, variantCount())];
	}

	private static final float[][] PALETTES = {
		{0.176F, 0.898F, 0.490F, 0.404F, 0.176F, 0.898F, 0.898F, 0.176F, 0.467F, 0.800F, 0.898F, 0.176F},
		{0.898F, 0.176F, 0.690F, 0.898F, 0.686F, 0.176F, 0.176F, 0.898F, 0.400F, 0.176F, 0.420F, 0.898F},
		{0.176F, 0.655F, 0.898F, 0.714F, 0.176F, 0.898F, 0.898F, 0.176F, 0.212F, 0.408F, 0.898F, 0.176F},
		{0.898F, 0.176F, 0.349F, 0.792F, 0.898F, 0.176F, 0.176F, 0.898F, 0.620F, 0.200F, 0.176F, 0.898F},
		{0.176F, 0.522F, 0.898F, 0.898F, 0.176F, 0.898F, 0.898F, 0.306F, 0.176F, 0.251F, 0.898F, 0.176F},
	};

	public static float[] palette(int dim) {
		if (dim < 0 || dim >= PALETTES.length) return null;
		return PALETTES[dim];
	}

	private BTTGeneratedContent() { }
}
