package com.beyondthelimits.world;

import com.beyondthelimits.BeyondTheLimits;
import com.beyondthelimits.util.BtlSafe;
import java.util.Optional;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.structure.StructurePlacementData;
import net.minecraft.structure.StructureTemplate;
import net.minecraft.structure.StructureTemplateManager;
import net.minecraft.util.BlockMirror;
import net.minecraft.util.BlockRotation;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.BlockPos;

/**
 * Runtime structure placement.
 *
 * <p>This is the workhorse behind most of the mod's biggest set pieces. Instead of generating
 * terrain in Java, Chapter One ships its architecture as structure templates ({@code .nbt} files
 * generated by {@code tools/generate_structures.py}) and stamps them into the world at runtime —
 * which is how the Old City, the warehouse gate, the Backrooms rooms, the substrata layers, the
 * ancient civilization, the collision events and the Last Chunk monument all exist without a single
 * custom feature class.</p>
 *
 * <p>It also lets the mod place structures <em>at any time</em>, not only during world generation:
 * that is what makes the world feel like it is being rewritten around the player rather than rolled
 * once at seed time.</p>
 */
public final class StructurePlacer {
	private StructurePlacer() {
	}

	public static final BlockRotation[] ROTATIONS = {
			BlockRotation.NONE, BlockRotation.CLOCKWISE_90, BlockRotation.CLOCKWISE_180, BlockRotation.COUNTERCLOCKWISE_90
	};

	public static boolean place(ServerWorld world, String path, BlockPos pos, BlockRotation rotation,
			boolean withEntities) {
		return place(world, BeyondTheLimits.id(path), pos, rotation, withEntities);
	}

	public static boolean place(ServerWorld world, Identifier id, BlockPos pos, BlockRotation rotation,
			boolean withEntities) {
		return BtlSafe.supply("structure.place:" + id.getPath(), () -> {
			StructureTemplateManager manager = world.getStructureTemplateManager();
			Optional<StructureTemplate> template = manager.getTemplate(id);

			if (template.isEmpty()) {
				return false;
			}

			StructurePlacementData data = new StructurePlacementData()
					.setRotation(rotation)
					.setMirror(BlockMirror.NONE)
					.setIgnoreEntities(!withEntities)
					.setUpdateNeighbors(false);

			return template.get().place(world, pos, pos, data, world.getRandom(), 2);
		}, false);
	}

	/** Places a structure centred on the given position. */
	public static boolean placeCentred(ServerWorld world, String path, BlockPos pos, BlockRotation rotation,
			boolean withEntities) {
		return place(world, path, pos.add(-8, 0, -8), rotation, withEntities);
	}

	/** Reads the size of a structure without placing it, used by engines that need footprints. */
	public static BlockPos sizeOf(ServerWorld world, String path) {
		return BtlSafe.supply("structure.size:" + path, () -> {
			Optional<StructureTemplate> template = world.getStructureTemplateManager().getTemplate(BeyondTheLimits.id(path));
			return template.map(structureTemplate -> {
				var size = structureTemplate.getSize();
				return new BlockPos(size.getX(), size.getY(), size.getZ());
			}).orElse(BlockPos.ORIGIN);
		}, BlockPos.ORIGIN);
	}

	public static BlockRotation randomRotation(ServerWorld world) {
		return ROTATIONS[world.getRandom().nextInt(ROTATIONS.length)];
	}
}
