package dev.logan.entersift.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** GENERATED by tools/creatures.py — edit the specs there, not this file. */
public final class SiftModelDefs {
    private SiftModelDefs() {}

    public static LayerDefinition blub() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-5.0f, -8.0f, -5.0f, 10.0f, 8.0f, 10.0f), PartPose.offsetAndRotation(0.0f, 21.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_ear_l = p_body.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(40, 0).addBox(-1.5f, -7.0f, -0.5f, 3.0f, 7.0f, 1.0f), PartPose.offsetAndRotation(-3.0f, -8.0f, 1.0f, 0.2f, 0.0f, -0.25f));
        PartDefinition p_ear_r = p_body.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(48, 0).addBox(-1.5f, -7.0f, -0.5f, 3.0f, 7.0f, 1.0f), PartPose.offsetAndRotation(3.0f, -8.0f, 1.0f, 0.2f, 0.0f, 0.25f));
        PartDefinition p_leg_0 = root.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(56, 0).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 3.0f, 2.0f), PartPose.offsetAndRotation(-3.0f, 21.0f, -3.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_1 = root.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(0, 18).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 3.0f, 2.0f), PartPose.offsetAndRotation(3.0f, 21.0f, -3.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_2 = root.addOrReplaceChild("leg_2", CubeListBuilder.create().texOffs(8, 18).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 3.0f, 2.0f), PartPose.offsetAndRotation(-3.0f, 21.0f, 3.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_3 = root.addOrReplaceChild("leg_3", CubeListBuilder.create().texOffs(16, 18).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 3.0f, 2.0f), PartPose.offsetAndRotation(3.0f, 21.0f, 3.0f, 0.0f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 64, 64);
    }
    public static final String[][] BLUB_PARTS = {{"body"}, {"body", "ear_l"}, {"body", "ear_r"}, {"leg_0"}, {"leg_1"}, {"leg_2"}, {"leg_3"}};

    public static LayerDefinition sculker() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_leg_0 = root.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(116, 0).addBox(-1.5f, 0.0f, -1.5f, 3.0f, 8.0f, 3.0f), PartPose.offsetAndRotation(-2.5f, 16.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_1 = root.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(0, 15).addBox(-1.5f, 0.0f, -1.5f, 3.0f, 8.0f, 3.0f), PartPose.offsetAndRotation(2.5f, 16.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(44, 0).addBox(-4.0f, -8.0f, -3.0f, 8.0f, 8.0f, 6.0f), PartPose.offsetAndRotation(0.0f, 16.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-6.0f, -5.0f, -5.0f, 12.0f, 5.0f, 10.0f), PartPose.offsetAndRotation(0.0f, -8.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_jaw = p_head.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(72, 0).addBox(-6.0f, 0.0f, -4.0f, 12.0f, 3.0f, 10.0f), PartPose.offsetAndRotation(0.0f, 0.0f, -1.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_whisker_l = p_head.addOrReplaceChild("whisker_l", CubeListBuilder.create().texOffs(20, 15).addBox(-5.0f, 0.0f, 0.0f, 5.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(-6.0f, -2.0f, -2.0f, 0.0f, 0.0f, 0.3f));
        PartDefinition p_whisker_r = p_head.addOrReplaceChild("whisker_r", CubeListBuilder.create().texOffs(32, 15).addBox(0.0f, 0.0f, 0.0f, 5.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(6.0f, -2.0f, -2.0f, 0.0f, 0.0f, -0.3f));
        PartDefinition p_antenna_l = p_head.addOrReplaceChild("antenna_l", CubeListBuilder.create().texOffs(12, 15).addBox(-0.5f, -6.0f, -0.5f, 1.0f, 6.0f, 1.0f).texOffs(44, 15).addBox(-2.5f, -5.0f, -0.5f, 2.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(-2.0f, -5.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_antenna_r = p_head.addOrReplaceChild("antenna_r", CubeListBuilder.create().texOffs(16, 15).addBox(-0.5f, -6.0f, -0.5f, 1.0f, 6.0f, 1.0f).texOffs(50, 15).addBox(0.5f, -4.0f, -0.5f, 2.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(2.0f, -5.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 128, 128);
    }
    public static final String[][] SCULKER_PARTS = {{"leg_0"}, {"leg_1"}, {"body"}, {"body", "head"}, {"body", "head", "jaw"}, {"body", "head", "whisker_l"}, {"body", "head", "whisker_r"}, {"body", "head", "antenna_l"}, {"body", "head", "antenna_r"}};

    public static LayerDefinition sculkling() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0f, -4.0f, -3.0f, 6.0f, 5.0f, 6.0f), PartPose.offsetAndRotation(0.0f, 21.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(24, 0).addBox(-3.0f, -5.0f, -3.0f, 6.0f, 5.0f, 5.0f), PartPose.offsetAndRotation(0.0f, -4.0f, -1.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_antenna_0 = p_head.addOrReplaceChild("antenna_0", CubeListBuilder.create().texOffs(46, 0).addBox(-0.5f, -3.0f, -0.5f, 1.0f, 3.0f, 1.0f).texOffs(24, 11).addBox(-1.5f, -4.0f, -0.5f, 3.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(0.0f, -5.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_0 = root.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(50, 0).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(-2.0f, 22.0f, -2.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_1 = root.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(0, 11).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(2.0f, 22.0f, -2.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_2 = root.addOrReplaceChild("leg_2", CubeListBuilder.create().texOffs(8, 11).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(-2.0f, 22.0f, 2.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_3 = root.addOrReplaceChild("leg_3", CubeListBuilder.create().texOffs(16, 11).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(2.0f, 22.0f, 2.0f, 0.0f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 64, 64);
    }
    public static final String[][] SCULKLING_PARTS = {{"body"}, {"body", "head"}, {"body", "head", "antenna_0"}, {"leg_0"}, {"leg_1"}, {"leg_2"}, {"leg_3"}};

    public static LayerDefinition antlerling() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_leg_0 = root.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(0, 16).addBox(-2.0f, 0.0f, -2.0f, 4.0f, 6.0f, 4.0f), PartPose.offsetAndRotation(-2.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_1 = root.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(16, 16).addBox(-2.0f, 0.0f, -2.0f, 4.0f, 6.0f, 4.0f), PartPose.offsetAndRotation(2.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 0).addBox(-4.0f, -9.0f, -3.0f, 8.0f, 9.0f, 6.0f), PartPose.offsetAndRotation(0.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_arms = p_body.addOrReplaceChild("arms", CubeListBuilder.create().texOffs(0, 26).addBox(-5.0f, -1.0f, -2.0f, 10.0f, 3.0f, 3.0f).texOffs(34, 26).addBox(-2.0f, 2.0f, -2.0f, 4.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(0.0f, -7.0f, -2.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0f, -8.0f, -4.0f, 8.0f, 8.0f, 8.0f).texOffs(26, 26).addBox(-1.0f, -4.0f, -6.0f, 2.0f, 4.0f, 2.0f), PartPose.offsetAndRotation(0.0f, -9.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_antler_l = p_head.addOrReplaceChild("antler_l", CubeListBuilder.create().texOffs(32, 16).addBox(-0.5f, -7.0f, -0.5f, 1.0f, 7.0f, 1.0f).texOffs(54, 26).addBox(-3.5f, -6.0f, -0.5f, 3.0f, 1.0f, 1.0f).texOffs(46, 26).addBox(-2.5f, -9.0f, -0.5f, 1.0f, 3.0f, 1.0f), PartPose.offsetAndRotation(-3.0f, -8.0f, 0.0f, 0.0f, 0.0f, -0.25f));
        PartDefinition p_antler_r = p_head.addOrReplaceChild("antler_r", CubeListBuilder.create().texOffs(36, 16).addBox(-0.5f, -7.0f, -0.5f, 1.0f, 7.0f, 1.0f).texOffs(0, 32).addBox(0.5f, -6.0f, -0.5f, 3.0f, 1.0f, 1.0f).texOffs(50, 26).addBox(1.5f, -9.0f, -0.5f, 1.0f, 3.0f, 1.0f), PartPose.offsetAndRotation(3.0f, -8.0f, 0.0f, 0.0f, 0.0f, 0.25f));
        return LayerDefinition.create(mesh, 64, 64);
    }
    public static final String[][] ANTLERLING_PARTS = {{"leg_0"}, {"leg_1"}, {"body"}, {"body", "arms"}, {"body", "head"}, {"body", "head", "antler_l"}, {"body", "head", "antler_r"}};

    public static LayerDefinition driftJelly() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-5.0f, -8.0f, -5.0f, 10.0f, 8.0f, 10.0f).texOffs(8, 18).addBox(-5.0f, 0.0f, -5.0f, 10.0f, 2.0f, 10.0f), PartPose.offsetAndRotation(0.0f, -14.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_0 = p_head.addOrReplaceChild("tentacle_0", CubeListBuilder.create().texOffs(40, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(-3.5f, 2.0f, -3.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_1 = p_head.addOrReplaceChild("tentacle_1", CubeListBuilder.create().texOffs(44, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(0.0f, 2.0f, -3.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_2 = p_head.addOrReplaceChild("tentacle_2", CubeListBuilder.create().texOffs(48, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(3.5f, 2.0f, -3.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_3 = p_head.addOrReplaceChild("tentacle_3", CubeListBuilder.create().texOffs(52, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(-3.5f, 2.0f, 3.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_4 = p_head.addOrReplaceChild("tentacle_4", CubeListBuilder.create().texOffs(56, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(0.0f, 2.0f, 3.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_5 = p_head.addOrReplaceChild("tentacle_5", CubeListBuilder.create().texOffs(60, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(3.5f, 2.0f, 3.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_6 = p_head.addOrReplaceChild("tentacle_6", CubeListBuilder.create().texOffs(0, 18).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(-3.5f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_7 = p_head.addOrReplaceChild("tentacle_7", CubeListBuilder.create().texOffs(4, 18).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 14.0f, 1.0f), PartPose.offsetAndRotation(3.5f, 2.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 64, 64);
    }
    public static final String[][] DRIFT_JELLY_PARTS = {{"head"}, {"head", "tentacle_0"}, {"head", "tentacle_1"}, {"head", "tentacle_2"}, {"head", "tentacle_3"}, {"head", "tentacle_4"}, {"head", "tentacle_5"}, {"head", "tentacle_6"}, {"head", "tentacle_7"}};

    public static LayerDefinition licker() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_leg_0 = root.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(92, 0).addBox(-1.5f, 0.0f, -1.5f, 3.0f, 4.0f, 3.0f), PartPose.offsetAndRotation(-4.0f, 20.0f, -3.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_1 = root.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(104, 0).addBox(-1.5f, 0.0f, -1.5f, 3.0f, 4.0f, 3.0f), PartPose.offsetAndRotation(4.0f, 20.0f, -3.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_2 = root.addOrReplaceChild("leg_2", CubeListBuilder.create().texOffs(116, 0).addBox(-1.5f, 0.0f, -1.5f, 3.0f, 4.0f, 3.0f), PartPose.offsetAndRotation(-4.0f, 20.0f, 4.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_3 = root.addOrReplaceChild("leg_3", CubeListBuilder.create().texOffs(0, 27).addBox(-1.5f, 0.0f, -1.5f, 3.0f, 4.0f, 3.0f), PartPose.offsetAndRotation(4.0f, 20.0f, 4.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-7.0f, -13.0f, -7.0f, 14.0f, 13.0f, 14.0f), PartPose.offsetAndRotation(0.0f, 20.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_crown = p_head.addOrReplaceChild("crown", CubeListBuilder.create().texOffs(12, 27).addBox(-2.0f, -2.0f, -2.0f, 4.0f, 2.0f, 4.0f).texOffs(28, 27).addBox(-1.0f, -4.0f, -1.0f, 1.0f, 2.0f, 1.0f).texOffs(32, 27).addBox(1.0f, -3.0f, 0.0f, 1.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(0.0f, -13.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tongue = p_head.addOrReplaceChild("tongue", CubeListBuilder.create().texOffs(68, 0).addBox(-2.5f, 0.0f, -1.0f, 5.0f, 1.0f, 7.0f).texOffs(56, 0).addBox(-2.5f, 0.0f, -8.0f, 5.0f, 8.0f, 1.0f), PartPose.offsetAndRotation(0.0f, -3.0f, -7.0f, 0.15f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 128, 128);
    }
    public static final String[][] LICKER_PARTS = {{"leg_0"}, {"leg_1"}, {"leg_2"}, {"leg_3"}, {"head"}, {"head", "crown"}, {"head", "tongue"}};

    public static LayerDefinition overseer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-6.0f, -12.0f, -6.0f, 12.0f, 12.0f, 12.0f), PartPose.offsetAndRotation(0.0f, -8.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_horn_l = p_head.addOrReplaceChild("horn_l", CubeListBuilder.create().texOffs(100, 0).addBox(-6.0f, -1.0f, -1.0f, 6.0f, 2.0f, 2.0f).texOffs(84, 0).addBox(-8.0f, -9.0f, -1.0f, 2.0f, 10.0f, 2.0f).texOffs(116, 0).addBox(-6.0f, -11.0f, -1.0f, 2.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(-6.0f, -8.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_horn_r = p_head.addOrReplaceChild("horn_r", CubeListBuilder.create().texOffs(0, 24).addBox(0.0f, -1.0f, -1.0f, 6.0f, 2.0f, 2.0f).texOffs(92, 0).addBox(6.0f, -9.0f, -1.0f, 2.0f, 10.0f, 2.0f).texOffs(16, 24).addBox(4.0f, -11.0f, -1.0f, 2.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(6.0f, -8.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(68, 0).addBox(-2.0f, 0.0f, -2.0f, 4.0f, 12.0f, 4.0f), PartPose.offsetAndRotation(0.0f, -8.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_arm_l = root.addOrReplaceChild("arm_l", CubeListBuilder.create().texOffs(24, 24).addBox(-12.0f, 0.0f, -1.0f, 12.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(-2.0f, -6.0f, 0.0f, 0.0f, 0.0f, -0.5f));
        PartDefinition p_arm_r = root.addOrReplaceChild("arm_r", CubeListBuilder.create().texOffs(52, 24).addBox(0.0f, 0.0f, -1.0f, 12.0f, 2.0f, 2.0f), PartPose.offsetAndRotation(2.0f, -6.0f, 0.0f, 0.0f, 0.0f, 0.5f));
        PartDefinition p_tentacle_0 = root.addOrReplaceChild("tentacle_0", CubeListBuilder.create().texOffs(48, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 18.0f, 1.0f), PartPose.offsetAndRotation(-1.5f, 4.0f, -1.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_1 = root.addOrReplaceChild("tentacle_1", CubeListBuilder.create().texOffs(52, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 18.0f, 1.0f), PartPose.offsetAndRotation(1.5f, 4.0f, -1.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_2 = root.addOrReplaceChild("tentacle_2", CubeListBuilder.create().texOffs(56, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 18.0f, 1.0f), PartPose.offsetAndRotation(-1.5f, 4.0f, 1.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_3 = root.addOrReplaceChild("tentacle_3", CubeListBuilder.create().texOffs(60, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 18.0f, 1.0f), PartPose.offsetAndRotation(1.5f, 4.0f, 1.5f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_tentacle_4 = root.addOrReplaceChild("tentacle_4", CubeListBuilder.create().texOffs(64, 0).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 18.0f, 1.0f), PartPose.offsetAndRotation(0.0f, 4.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 128, 128);
    }
    public static final String[][] OVERSEER_PARTS = {{"head"}, {"head", "horn_l"}, {"head", "horn_r"}, {"body"}, {"arm_l"}, {"arm_r"}, {"tentacle_0"}, {"tentacle_1"}, {"tentacle_2"}, {"tentacle_3"}, {"tentacle_4"}};

    public static LayerDefinition twistedWarden() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_leg_0 = root.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(52, 34).addBox(-3.0f, 0.0f, -3.0f, 6.0f, 13.0f, 6.0f), PartPose.offsetAndRotation(-5.0f, 11.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_1 = root.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(76, 34).addBox(-3.0f, 0.0f, -3.0f, 6.0f, 13.0f, 6.0f), PartPose.offsetAndRotation(5.0f, 11.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(64, 0).addBox(-9.0f, -21.0f, -5.0f, 18.0f, 21.0f, 10.0f), PartPose.offsetAndRotation(0.0f, 11.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_chest_upper = p_body.addOrReplaceChild("chest_upper", CubeListBuilder.create().texOffs(0, 71).addBox(-8.0f, 0.0f, -2.0f, 16.0f, 3.0f, 2.0f).texOffs(64, 76).addBox(-7.0f, 3.0f, -2.0f, 2.0f, 2.0f, 1.0f).texOffs(70, 76).addBox(-3.0f, 3.0f, -2.0f, 2.0f, 2.0f, 1.0f).texOffs(76, 76).addBox(1.0f, 3.0f, -2.0f, 2.0f, 2.0f, 1.0f).texOffs(82, 76).addBox(5.0f, 3.0f, -2.0f, 2.0f, 2.0f, 1.0f), PartPose.offsetAndRotation(0.0f, -16.0f, -5.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_chest_lower = p_body.addOrReplaceChild("chest_lower", CubeListBuilder.create().texOffs(36, 71).addBox(-8.0f, -3.0f, -2.0f, 16.0f, 3.0f, 2.0f).texOffs(88, 76).addBox(-5.0f, -5.0f, -2.0f, 2.0f, 2.0f, 1.0f).texOffs(94, 76).addBox(-1.0f, -5.0f, -2.0f, 2.0f, 2.0f, 1.0f).texOffs(100, 76).addBox(3.0f, -5.0f, -2.0f, 2.0f, 2.0f, 1.0f), PartPose.offsetAndRotation(0.0f, -4.0f, -5.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 34).addBox(-7.0f, -12.0f, -6.0f, 14.0f, 12.0f, 12.0f), PartPose.offsetAndRotation(0.0f, -21.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_horn_l = p_head.addOrReplaceChild("horn_l", CubeListBuilder.create().texOffs(80, 58).addBox(-1.0f, -10.0f, -1.0f, 2.0f, 10.0f, 2.0f).texOffs(88, 71).addBox(-10.0f, -10.0f, -1.0f, 9.0f, 2.0f, 2.0f).texOffs(88, 58).addBox(-10.0f, -20.0f, -1.0f, 2.0f, 10.0f, 2.0f).texOffs(110, 71).addBox(-10.0f, -20.0f, -1.0f, 7.0f, 2.0f, 2.0f).texOffs(112, 58).addBox(-5.0f, -16.0f, -1.0f, 2.0f, 6.0f, 2.0f).texOffs(0, 76).addBox(-14.0f, -15.0f, -1.0f, 4.0f, 2.0f, 2.0f).texOffs(72, 71).addBox(-14.0f, -18.0f, -1.0f, 2.0f, 3.0f, 2.0f), PartPose.offsetAndRotation(-4.0f, -12.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_horn_r = p_head.addOrReplaceChild("horn_r", CubeListBuilder.create().texOffs(96, 58).addBox(-1.0f, -10.0f, -1.0f, 2.0f, 10.0f, 2.0f).texOffs(12, 76).addBox(1.0f, -10.0f, -1.0f, 9.0f, 2.0f, 2.0f).texOffs(104, 58).addBox(8.0f, -20.0f, -1.0f, 2.0f, 10.0f, 2.0f).texOffs(34, 76).addBox(3.0f, -20.0f, -1.0f, 7.0f, 2.0f, 2.0f).texOffs(120, 58).addBox(3.0f, -16.0f, -1.0f, 2.0f, 6.0f, 2.0f).texOffs(52, 76).addBox(10.0f, -15.0f, -1.0f, 4.0f, 2.0f, 2.0f).texOffs(80, 71).addBox(12.0f, -18.0f, -1.0f, 2.0f, 3.0f, 2.0f), PartPose.offsetAndRotation(4.0f, -12.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_arm_l = p_body.addOrReplaceChild("arm_l", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0f, 0.0f, -4.0f, 8.0f, 26.0f, 8.0f).texOffs(0, 58).addBox(-5.0f, 19.0f, -5.0f, 10.0f, 3.0f, 10.0f), PartPose.offsetAndRotation(-13.0f, -17.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_arm_r = p_body.addOrReplaceChild("arm_r", CubeListBuilder.create().texOffs(32, 0).addBox(-4.0f, 0.0f, -4.0f, 8.0f, 26.0f, 8.0f).texOffs(40, 58).addBox(-5.0f, 19.0f, -5.0f, 10.0f, 3.0f, 10.0f), PartPose.offsetAndRotation(13.0f, -17.0f, 1.0f, 0.0f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 128, 128);
    }
    public static final String[][] TWISTED_WARDEN_PARTS = {{"leg_0"}, {"leg_1"}, {"body"}, {"body", "chest_upper"}, {"body", "chest_lower"}, {"body", "head"}, {"body", "head", "horn_l"}, {"body", "head", "horn_r"}, {"body", "arm_l"}, {"body", "arm_r"}};

    public static LayerDefinition noteBird() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.0f, -3.0f, -3.0f, 4.0f, 3.0f, 6.0f).texOffs(20, 9).addBox(-1.5f, -2.0f, 3.0f, 3.0f, 1.0f, 3.0f), PartPose.offsetAndRotation(0.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(20, 0).addBox(-1.5f, -3.0f, -2.0f, 3.0f, 3.0f, 3.0f).texOffs(40, 9).addBox(-0.5f, -1.5f, -3.0f, 1.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(0.0f, -3.0f, -2.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_wing_l = p_body.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(32, 0).addBox(-6.0f, 0.0f, -2.0f, 6.0f, 1.0f, 4.0f), PartPose.offsetAndRotation(-2.0f, -2.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_wing_r = p_body.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(0, 9).addBox(0.0f, 0.0f, -2.0f, 6.0f, 1.0f, 4.0f), PartPose.offsetAndRotation(2.0f, -2.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_0 = root.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(32, 9).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 2.0f, 1.0f), PartPose.offsetAndRotation(-1.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_leg_1 = root.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(36, 9).addBox(-0.5f, 0.0f, -0.5f, 1.0f, 2.0f, 1.0f), PartPose.offsetAndRotation(1.0f, 18.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        return LayerDefinition.create(mesh, 64, 64);
    }
    public static final String[][] NOTE_BIRD_PARTS = {{"body"}, {"body", "head"}, {"body", "wing_l"}, {"body", "wing_r"}, {"leg_0"}, {"leg_1"}};

    public static LayerDefinition singer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0f, -22.0f, -3.0f, 8.0f, 22.0f, 6.0f).texOffs(68, 0).addBox(-5.0f, -7.0f, -4.0f, 10.0f, 7.0f, 8.0f), PartPose.offsetAndRotation(0.0f, 24.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(104, 0).addBox(-3.0f, -8.0f, -3.0f, 6.0f, 8.0f, 6.0f), PartPose.offsetAndRotation(0.0f, -22.0f, 0.0f, 0.0f, 0.0f, 0.0f));
        PartDefinition p_antler_l = p_head.addOrReplaceChild("antler_l", CubeListBuilder.create().texOffs(0, 28).addBox(-0.5f, -9.0f, -0.5f, 1.0f, 9.0f, 1.0f).texOffs(16, 28).addBox(-3.5f, -6.0f, -0.5f, 3.0f, 1.0f, 1.0f).texOffs(8, 28).addBox(-3.5f, -9.0f, -0.5f, 1.0f, 3.0f, 1.0f).texOffs(24, 28).addBox(0.5f, -8.0f, -0.5f, 2.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(-2.0f, -7.0f, 0.0f, 0.0f, 0.0f, -0.45f));
        PartDefinition p_antler_r = p_head.addOrReplaceChild("antler_r", CubeListBuilder.create().texOffs(4, 28).addBox(-0.5f, -9.0f, -0.5f, 1.0f, 9.0f, 1.0f).texOffs(30, 28).addBox(0.5f, -6.0f, -0.5f, 3.0f, 1.0f, 1.0f).texOffs(12, 28).addBox(2.5f, -9.0f, -0.5f, 1.0f, 3.0f, 1.0f).texOffs(38, 28).addBox(-2.5f, -8.0f, -0.5f, 2.0f, 1.0f, 1.0f), PartPose.offsetAndRotation(2.0f, -7.0f, 0.0f, 0.0f, 0.0f, 0.45f));
        PartDefinition p_arm_l = p_body.addOrReplaceChild("arm_l", CubeListBuilder.create().texOffs(28, 0).addBox(-2.0f, 0.0f, -4.0f, 2.0f, 16.0f, 8.0f), PartPose.offsetAndRotation(-4.0f, -20.0f, 0.0f, 0.0f, 0.0f, 0.55f));
        PartDefinition p_arm_r = p_body.addOrReplaceChild("arm_r", CubeListBuilder.create().texOffs(48, 0).addBox(0.0f, 0.0f, -4.0f, 2.0f, 16.0f, 8.0f), PartPose.offsetAndRotation(4.0f, -20.0f, 0.0f, 0.0f, 0.0f, -0.55f));
        return LayerDefinition.create(mesh, 128, 128);
    }
    public static final String[][] SINGER_PARTS = {{"body"}, {"body", "head"}, {"body", "head", "antler_l"}, {"body", "head", "antler_r"}, {"body", "arm_l"}, {"body", "arm_r"}};

}
